app:
  web:
    url: https://myworktime.vectoritcgroup.com # ruta de la web
    url-cita: https://sede.administracionespublicas.gob.es/icpplustiem/citar?p=28&locale=es
  web-driver:
    url: C:\Desarrollo\chromedriver_2.exe # ruta del chromedriver para el control de chrome
  directory:
    screen: C:\Desarrollo\capturas\ # ruta donde se guardaran las capturas de pantalla
  job:
    cron: 0 0 20 * * *
  jornada:
    iniciar-job: 0 0 8 * * MON-FRI # inicia jornada de lunes a viernes a las 8:00AM
    finalizar-lunes-jueves-job: 0 30 17 * * MON-THU # finalizar jornada a las 5:30PM
    finalizar-viernes-job: 0 0 15 * * FRI # finalizar jornada los viernes a las 3:00PM
  comida:
    iniciar-job: 0 30 14 * * MON-THU # iniciar comida a las 2:30PM de lunes a jueves
    finalizar-job: 0 30 15 * * MON-THU # finalizar jornada a las 3:30PM de lunes a jueves
  usr: areyesg # usuario de auntenticacion
  pass: Diciembre2021 # contrase√±a de autenticacionq

person:
  data:
    -
      name: EMILIO REYES GUEVARA
      passport: C11111111
      year-of-birth: 1993
      mail: aerguevaasra@gmail.com
      phone: 688246000
      nationality: 236

