spring:
  data:
    mongodb:
      user: devuser
      password: pass1234
      uri: mongodb://192.168.1.145:27017/develop
logging:
  file:
    name: auto.log
    max-size: 10MB
app:
  bot:
    url: http://localhost:5151/api/v1/notification
  web:
    url-cita: https://sede.administracionespublicas.gob.es/icpplustiem/citar?p=28&locale=es
  web-driver:
    url: C:\Desarrollo\MI_AMORCITO\chromedriver.exe # ruta del chromedriver para el control de chrome
  fixed-delay: "5000" #milesecond
  sleep-minute: 10
  job:
    cron: 0 0 20 * * *
    cron-spt: "0 0 */1 * * *"
    id: "1"

person:
  data:
    -
      name: AAAAAA AAAAA AAAAAAA
      passport: C11111111
      year-of-birth: 1993
      mail: aaaaaaaa@aaaaa.com
      phone: 666666666
      nationality: 236

